require "data.maps.map_1"

require "src.actions"
require "src.camera"
require "src.combat"
require "src.entity"
require "src.entitydefs"
require "src.float"
require "src.hud"
require "src.input"
require "src.itemDB"
require "src.inventory"
require "src.list"
require "src.map"
require "src.menu"
require "src.panel"
require "src.selection"
require "src.settings"
require "src.sprite"
require "src.sound"
require "src.statestack"
require "src.statemachine"
require "src.textbox"
require "src.tween"
require "src.utils"
require "src.world"

require "src.scenes.game"
require "src.scenes.gameover"

require "src.startup.loadresources"