require "data.maps.map_1"

require "src.Actions"
require "src.Camera"
require "src.Cast"
require "src.Combat"
require "src.Entity"
require "src.Entitydefs"
require "src.Float"
require "src.Hud"
require "src.Input"
require "src.ItemDB"
require "src.Inventory"
require "src.List"
require "src.Map"
require "src.Menu"
require "src.Panel"
require "src.Selection"
require "src.Settings"
require "src.SpellDB"
require "src.Sprite"
require "src.Sound"
require "src.StateStack"
require "src.StateMachine"
require "src.Textbox"
require "src.Tween"
require "src.Utils"
require "src.World"

require "src.scenes.Game"
require "src.scenes.GameOver"

require "src.startup.LoadResources"